name: Merge JSON Files

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  merge_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to v3 for Node.js 20 compatibility

      - name: Install Node.js
        uses: actions/setup-node@v3  # Update to v3 for Node.js 20 compatibility
        with:
          node-version: '20'

      - name: Merge JSON files from web
        run: |
          # Create a script to fetch and merge two JSON files from the web
          npm install node-fetch@2  # Install node-fetch to make HTTP requests

          # Write the script
          cat > merge-json.js <<EOF
          const fetch = require('node-fetch');
          const fs = require('fs');
          
          const url1 = 'https://cdn.flybywiresim.com/installer/config/production.json';  // Replace with the actual URL for file 1
          const url2 = 'https://cdn.headwindsim.net/installer/config/production.json';  // Replace with the actual URL for file 2
          const outputFile = 'OneInstaller.json';  // Local path where merged file will be saved

          async function mergeJSON() {
            try {
              const res1 = await fetch(url1);
              const res2 = await fetch(url2);
              
              const json1 = await res1.json();
              const json2 = await res2.json();

              const mergedJson = { ...json1, ...json2 };

              fs.writeFileSync(outputFile, JSON.stringify(mergedJson, null, 2));
              console.log('JSON files merged successfully');
            } catch (error) {
              console.error('Error fetching or merging JSON files:', error);
            }
          }

          mergeJSON();
          EOF

          # Run the script to merge JSON files
          node merge-json.js
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add OneInstaller.json
          git commit -m "Merged JSON files from web"
          git push
