name: Fetch and Merge JSON Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fetch_and_merge_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Fetch JSON files
      run: |
        mkdir -p ./data
        curl -o ./data/file1.json https://cdn.flybywiresim.com/installer/config/production.json
        curl -o ./data/file1.json https://cdn.flybywiresim.com/installer/config/production.json

    - name: Ensure output directory exists
      run: |
        mkdir -p ./output

    - name: Merge JSON files
      run: |
        node -e "
          const fs = require('fs');
          const path = require('path');

          // Function to merge JSON files
          const mergeJsonFiles = (inputDir, outputFile) => {
            const files = fs.readdirSync(inputDir).filter(file => file.endsWith('.json'));
            let mergedData = {};

            files.forEach(file => {
              const filePath = path.join(inputDir, file);
              const jsonData = JSON.parse(fs.readFileSync(filePath));
              mergedData = { ...mergedData, ...jsonData };
            });

            fs.writeFileSync(outputFile, JSON.stringify(mergedData, null, 2));
            console.log('JSON files merged successfully!');
          };

          // Define input directory and output file
          const inputDir = './data'; // Directory with fetched JSON files
          const outputFile = './output/merged.json'; // Desired output path

          mergeJsonFiles(inputDir, outputFile);
        "

    - name: Commit and push changes
      run: |
        git config --local user.email "your_email@example.com"
        git config --local user.name "Your Name"
        git add output/merged.json
        git commit -m "Fetch and merge JSON files"
        git push
